export const footerConstants = [
  "Sign Up",
  "Log in",
  "Messenger",
  "Facebook Lite",
  "Video",
  "Places",
  "Games",
  "Marketplace",
  "Meta Pay",
  "Meta Store",
  "Meta Quest",
  "Instagram",
  "Threads",
  "Fundraisers",
  "Services",
  "Voting",
  "Information Centre",
  "Privacy Policy",
  "Privacy Centre",
  "Groups",
  "About",
  "Create ad",
  "Create Page",
  "Developers",
  "Careers",
  "Cookies",
  "AdChoices",
  "Terms",
  "Help",
  "Contact uploading and non-users",
];
